[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    MinUnstakeTokensValue = "10000000000000000000" #10eGLD
    UnBondPeriod = 2400
    UnBondPeriodInEpochs = 1
    MinStepValue = "100000000000000000000"
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 320
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = true

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd17x5h63fgentz5302m9rd7ryttssttk68xtpr9qdztssw88vfs07s65w8dc"

[GovernanceSystemSCConfig]
    FirstWhitelistedAddress = "erd1uwd7czafqa2eka354h8y9slx4t8da7sf3d0nce6yj3rnf72j63ns8v5uef" #should use a multisign contract instead of a wallet address
    [GovernanceSystemSCConfig.V1]
        NumNodes           = 500
        ProposalCost       = "5000000000000000000" #5 eGLD
        MinQuorum          = 400
        MinPassThreshold   = 300
        MinVetoThreshold   = 50
    [GovernanceSystemSCConfig.Active]
        ProposalCost       = "5000000000000000000" #5 eGLD
        MinQuorum          = "500000000000" # MinQuorum is equal to 10*sqrt(NodePrice)
        MinPassThreshold   = "251000000000"
        MinVetoThreshold   = "249000000000"

[DelegationManagerSystemSCConfig]
    MinCreationDeposit = "1250000000000000000000" #1.25K eGLD
    MinStakeAmount = "1000000000000000000" #1 eGLD
    ConfigChangeAddress = "erd1tsgw76rcawsdp703qh25vezkpmley8xu6k6wx3jngru470rqu2rq5lqmjd" #should use a multisign contract instead of a wallet address

[DelegationSystemSCConfig]
    MinServiceFee  = 0
    MaxServiceFee  = 10000
